---
apiVersion: stargate.io/v1alpha1
kind: Operation
metadata:
  name: repave-server-001
  namespace: dc-west
spec:
  serverRef:
    name: server-001
  provisioningProfileRef:
    name: os-2-0-0
  operation: repave
