---
apiVersion: stargate.io/v1alpha1
kind: Operation
metadata:
  name: repave-server-001
  namespace: default
spec:
  serverRef:
    # Name of the Server CR to repave
    name: stargate-azure-vm25-1
  provisioningProfileRef:
    # Name of the ProvisioningProfile that defines bootstrap config
    name: azure-k8s-worker
  operation: repave
