---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servers.stargate.io
spec:
  group: stargate.io
  names:
    kind: Server
    listKind: ServerList
    plural: servers
    singular: server
    shortNames:
      - srv
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - mac
              properties:
                mac:
                  type: string
                  description: MAC address of the server's primary NIC
                ipv4:
                  type: string
                  description: IPv4 address of the server
                bmc:
                  type: object
                  properties:
                    address:
                      type: string
                      description: Address of the BMC (IP or hostname)
                    credentialSecretRef:
                      type: string
                      description: Reference to Secret containing BMC credentials
                inventory:
                  type: object
                  properties:
                    sku:
                      type: string
                      description: SKU of the server
                    location:
                      type: string
                      description: Location within the datacenter
                    serialNumber:
                      type: string
                      description: Serial number of the server
            status:
              type: object
              properties:
                state:
                  type: string
                  description: "State of the server: ready, provisioning, error"
                currentOS:
                  type: string
                  description: Current OS version running on the server
                lastUpdated:
                  type: string
                  format: date-time
                  description: Last time the status was updated
                message:
                  type: string
                  description: Additional status information
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: State
          type: string
          jsonPath: .status.state
        - name: OS
          type: string
          jsonPath: .status.currentOS
        - name: IPv4
          type: string
          jsonPath: .spec.ipv4
